version: '3.6'


volumes:
  mongodb_data_01:


services:
  app_group_01:
    container_name: app_group_01
    image: app_group_01:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://group_01:admin@mongodb_01/admin
    ports:
      - 8021:8080
    restart: unless-stopped

  mongodb_01:
    container_name: mongodb_01
    image: mongo:latest
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=group_01
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb_data_01:/data/db
    ports: 
      - 8012:27017
    restart: unless-stopped

  mongo_express_01:
    container_name: mongo_express_01
    image: mongo-express:latest
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=monokai
      - ME_CONFIG_MONGODB_SERVER=mongodb_01
      - ME_CONFIG_MONGODB_ADMINUSERNAME=group_01
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_BASICAUTH_USERNAME=group_01
      - ME_CONFIG_BASICAUTH_PASSWORD=Web!0
    ports:
      - 8013:8081
    restart: unless-stopped
