version: '3.6'


services:
  app_group_01:
    container_name: app_group_01
    image: app_group_01:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://group_01:admin@80.77.225.39:8012/admin
    ports:
      - 8021:8080
    restart: unless-stopped
